branch-defaults:
  default:
    environment: App-Server-dev
global:
  application_name: App-Server
  default_ec2_keyname: bkj2111MiniHw2
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: null
